// Generated by CoffeeScript 1.7.1
(function() {
  var AttendantAdapter, AttendantUtilities, BaseAttendant, DocumentPropertiesAttendant, Enum, LoggerAttendant, PropertiesAttendant, PropertiesServiceAttendant, RangeAttendant, RangeAttendantIterator, RangeColumnIterator, RangeRowIterator, ScriptPropertiesAttendant, Severity, SheetAppender, SheetAttendant, SheetIterator, SpreadsheetAppAttendant, SpreadsheetAttendant, TypeHelper, UserPropertiesAttendant, root,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  AttendantUtilities = (function() {
    function AttendantUtilities() {}

    AttendantUtilities.merge = function(left, right) {
      var property;
      if (left == null) {
        left = right;
        return left;
      }
      for (property in right) {
        if (AttendantUtilities.type(right[property]) === 'object') {
          if (AttendantUtilities.type(left[property]) === 'object') {
            left[property] = AttendantUtilities.merge(left[property], right[property]);
          } else {
            left[property] = right[property];
          }
        } else {
          left[property] = right[property];
        }
      }
      return left;
    };

    AttendantUtilities.reverseMerge = function(left, right) {
      return AttendantUtilities.merge(right, left);
    };

    AttendantUtilities.type = function(obj) {
      var classToType;
      if (obj === void 0 || obj === null) {
        return String(obj);
      }
      classToType = {
        '[object Boolean]': 'boolean',
        '[object Number]': 'number',
        '[object String]': 'string',
        '[object Function]': 'function',
        '[object Array]': 'array',
        '[object Date]': 'date',
        '[object RegExp]': 'regexp',
        '[object Object]': 'object'
      };
      return classToType[Object.prototype.toString.call(obj)];
    };

    AttendantUtilities.fetchDeep = function() {
      var fields, obj, reducer;
      obj = arguments[0], fields = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      reducer = function(prev, curr) {
        return prev[curr];
      };
      return fields.reduce(reducer, obj);
    };

    AttendantUtilities.mixOf = function() {
      var Mixed, base, method, mixin, mixins, name, _i, _ref;
      base = arguments[0], mixins = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      Mixed = (function(_super) {
        __extends(Mixed, _super);

        function Mixed() {
          return Mixed.__super__.constructor.apply(this, arguments);
        }

        return Mixed;

      })(base);
      for (_i = mixins.length - 1; _i >= 0; _i += -1) {
        mixin = mixins[_i];
        _ref = mixin.prototype;
        for (name in _ref) {
          method = _ref[name];
          Mixed.prototype[name] = method;
        }
      }
      return Mixed;
    };

    return AttendantUtilities;

  })();

  TypeHelper = (function() {
    function TypeHelper() {}

    TypeHelper.isRange = function(object) {
      return object.toString() === 'Range';
    };

    TypeHelper.isSpreadsheet = function(object) {
      return object.toString() === 'Spreadsheet';
    };

    TypeHelper.isSheet = function(object) {
      return object.toString() === 'Sheet';
    };

    TypeHelper.isScriptProperties = function(object) {
      return object.toString() === 'ScriptProperties';
    };

    TypeHelper.isUserProperties = function(object) {
      return object.toString() === 'UserProperties';
    };

    TypeHelper.isDocumentProperties = function(object) {
      return object.toString() === 'DocumentProperties';
    };

    return TypeHelper;

  })();

  AttendantAdapter = (function() {
    function AttendantAdapter() {}

    AttendantAdapter.override = function(object) {
      switch (object.toString()) {
        case 'Range':
          return new RangeAttendant(object);
        case 'Spreadsheet':
          return new SpreadsheetAttendant(object);
        case 'Sheet':
          return new SheetAttendant(object);
        case 'ScriptProperties':
          return new ScriptPropertiesAttendant(object);
        case 'UserProperties':
          return new UserPropertiesAttendant(object);
        case 'DocumentProperties':
          return new DocumentPropertiesAttendant(object);
        default:
          return object;
      }
    };

    AttendantAdapter.proxyMethod = function(object, method, args) {
      var arg, castArguments, returnObject, _i, _len;
      if (object[method] == null) {
        throw new TypeError;
      }
      castArguments = [];
      for (_i = 0, _len = args.length; _i < _len; _i++) {
        arg = args[_i];
        castArguments.push(arg['_baseObject'] != null ? arg['_baseObject'] : arg);
      }
      returnObject = object[method].apply(object, castArguments);
      return AttendantAdapter.override(returnObject);
    };

    return AttendantAdapter;

  })();

  BaseAttendant = (function() {
    function BaseAttendant(_baseObject) {
      this._baseObject = _baseObject;
    }

    BaseAttendant.prototype.__noSuchMethod__ = function(id, args) {
      return AttendantAdapter.proxyMethod(this._baseObject, id, args);
    };

    return BaseAttendant;

  })();

  SheetIterator = (function() {
    function SheetIterator() {}

    SheetIterator.prototype.eachRow = function(callback) {
      this.getEntireRange().eachRow(callback);
      return this;
    };

    SheetIterator.prototype.eachRowReverse = function(callback) {
      this.getEntireRange().eachRowReverse(callback);
      return this;
    };

    SheetIterator.prototype.eachColumn = function(callback) {
      this.getEntireRange().eachColumn(callback);
      return this;
    };

    SheetIterator.prototype.eachColumnReverse = function(callback) {
      this.getEntireRange().eachColumnReverse(callback);
      return this;
    };

    SheetIterator.prototype.rowIterator = function() {
      return this.getEntireRange().rowIterator();
    };

    SheetIterator.prototype.columnIterator = function() {
      return this.getEntireRange().columnIterator();
    };

    SheetIterator.prototype.dataRowIterator = function() {
      return this.getDataRange().rowIterator();
    };

    SheetIterator.prototype.dataColumnIterator = function() {
      return this.getDataRange().columnIterator();
    };

    SheetIterator.prototype.eachDataRow = function(callback) {
      this.getDataRange().eachRow(callback);
      return this;
    };

    SheetIterator.prototype.eachDataRowReverse = function(callback) {
      this.getDataRange().eachRowReverse(callback);
      return this;
    };

    SheetIterator.prototype.eachDataColumn = function(callback) {
      this.getDataRange().eachColumn(callback);
      return this;
    };

    SheetIterator.prototype.eachDataColumnReverse = function(callback) {
      this.getDataRange().eachColumnReverse(callback);
      return this;
    };

    return SheetIterator;

  })();

  SheetAppender = (function() {
    function SheetAppender() {}

    SheetAppender.prototype.appendRowReturnRange = function(data) {
      var finder, row, rowIterator, sheet, values;
      sheet = this.appendRow(data);
      rowIterator = sheet.rowIterator().reverse();
      while (rowIterator.hasNext()) {
        row = rowIterator.next();
        values = row.getValues()[0];
        finder = function(value, index) {
          if (data[index] == null) {
            return true;
          }
          return value.valueOf() === data[index].valueOf();
        };
        if (values.every(finder)) {
          return row;
        }
      }
      return null;
    };

    return SheetAppender;

  })();

  SpreadsheetAttendant = (function(_super) {
    __extends(SpreadsheetAttendant, _super);

    function SpreadsheetAttendant() {
      return SpreadsheetAttendant.__super__.constructor.apply(this, arguments);
    }

    SpreadsheetAttendant.prototype.getEntireRange = function() {
      var sheet;
      sheet = this.getActiveSheet();
      return sheet.getRange(1, 1, sheet.getMaxRows(), sheet.getMaxColumns());
    };

    SpreadsheetAttendant.prototype.toString = function() {
      return "SpreadsheetAttendant";
    };

    return SpreadsheetAttendant;

  })(AttendantUtilities.mixOf(BaseAttendant, SheetIterator, SheetAppender));

  SheetAttendant = (function(_super) {
    __extends(SheetAttendant, _super);

    function SheetAttendant() {
      return SheetAttendant.__super__.constructor.apply(this, arguments);
    }

    SheetAttendant.prototype.getEntireRange = function() {
      return this.getRange(1, 1, this.getMaxRows(), this.getMaxColumns());
    };

    SheetAttendant.prototype.toString = function() {
      return "SheetAttendant";
    };

    return SheetAttendant;

  })(AttendantUtilities.mixOf(BaseAttendant, SheetIterator, SheetAppender));

  RangeAttendant = (function(_super) {
    __extends(RangeAttendant, _super);

    function RangeAttendant() {
      return RangeAttendant.__super__.constructor.apply(this, arguments);
    }

    RangeAttendant.prototype.isBlank = function() {
      var error, row, value, values, _i, _j, _len, _len1;
      try {
        return this.object.isBlank();
      } catch (_error) {
        error = _error;
        LoggerAttendant.debug('Built in Range.isBlank() failed trying backup');
        values = this.getValues();
        for (_i = 0, _len = values.length; _i < _len; _i++) {
          row = values[_i];
          for (_j = 0, _len1 = row.length; _j < _len1; _j++) {
            value = row[_j];
            if (value !== '') {
              return false;
            }
          }
        }
        return true;
      }
    };

    RangeAttendant.prototype.includeAllColumns = function() {
      var rowIndex, sheet;
      sheet = this.getSheet();
      rowIndex = this.getCell(1, 1).getRow();
      return sheet.getRange(rowIndex, 1, this.getNumRows(), sheet.getMaxColumns());
    };

    RangeAttendant.prototype.removeHeader = function() {
      if (this.getRow() === 1) {
        if (this.getNumRows() === 1) {
          return null;
        } else {
          return this.sliceRows(2);
        }
      } else {
        return this;
      }
    };

    RangeAttendant.prototype.sliceRows = function(start, length) {
      return this.slice(start, 1, length);
    };

    RangeAttendant.prototype.sliceColumns = function(start, length) {
      return this.slice(1, start, null, length);
    };

    RangeAttendant.prototype.slice = function(startRow, startColumn, rowLength, columnLength) {
      var startCell;
      if (rowLength == null) {
        rowLength = this.getNumRows() - startRow + 1;
      }
      if (columnLength == null) {
        columnLength = this.getNumColumns() - startColumn + 1;
      }
      if (startRow > this.getNumRows() || startColumn > this.getNumColumns()) {
        return this;
      }
      if (rowLength + startRow > this.getNumRows()) {
        rowLength = this.getNumRows() - startRow + 1;
      }
      if (columnLength + startColumn > this.getNumColumns()) {
        columnLength = this.getNumColumns() - startColumn + 1;
      }
      startCell = this.getCell(startRow, startColumn);
      return this.getSheet().getRange(startCell.getRow(), startCell.getColumn(), rowLength, columnLength);
    };

    RangeAttendant.prototype.rowIterator = function() {
      return new RangeRowIterator(this);
    };

    RangeAttendant.prototype.columnIterator = function() {
      return new RangeColumnIterator(this);
    };

    RangeAttendant.prototype.eachRow = function(callback) {
      var rowIterator;
      rowIterator = this.rowIterator();
      while (rowIterator.hasNext()) {
        callback(rowIterator.next(), rowIterator.currentIndex);
      }
      return this;
    };

    RangeAttendant.prototype.eachRowReverse = function(callback) {
      var rowIterator;
      rowIterator = this.rowIterator().reverse();
      while (rowIterator.hasNext()) {
        callback(rowIterator.next(), rowIterator.currentIndex);
      }
      return this;
    };

    RangeAttendant.prototype.eachColumn = function(callback) {
      var columnIterator;
      columnIterator = this.columnIterator();
      while (columnIterator.hasNext()) {
        callback(columnIterator.next(), columnIterator.currentIndex);
      }
      return this;
    };

    RangeAttendant.prototype.eachColumnReverse = function(callback) {
      var columnIterator;
      columnIterator = this.columnIterator().reverse();
      while (columnIterator.hasNext()) {
        callback(columnIterator.next(), columnIterator.currentIndex);
      }
      return this;
    };

    return RangeAttendant;

  })(BaseAttendant);

  RangeAttendantIterator = (function() {
    function RangeAttendantIterator(range) {
      this.range = range;
      this.currentIndex = 1;
      this.reversed = false;
    }

    RangeAttendantIterator.prototype.reverse = function() {
      this.currentIndex = this.getSize();
      this.reversed = !this.reversed;
      return this;
    };

    RangeAttendantIterator.prototype.hasNext = function() {
      if (this.reversed) {
        return this.currentIndex > 0;
      } else {
        return this.currentIndex <= this.getSize();
      }
    };

    RangeAttendantIterator.prototype.getSize = function() {};

    RangeAttendantIterator.prototype.next = function() {};

    RangeAttendantIterator.prototype.startAt = function(index) {
      if ((0 < index && index <= this.getSize())) {
        this.currentIndex = index;
      }
      return this;
    };

    return RangeAttendantIterator;

  })();

  RangeRowIterator = (function(_super) {
    __extends(RangeRowIterator, _super);

    function RangeRowIterator() {
      return RangeRowIterator.__super__.constructor.apply(this, arguments);
    }

    RangeRowIterator.prototype.getSize = function() {
      return this.range.getNumRows();
    };

    RangeRowIterator.prototype.next = function() {
      var columnIndex, firstCell, rowIndex, sheet;
      sheet = this.range.getSheet();
      firstCell = this.range.getCell(this.currentIndex, 1);
      rowIndex = firstCell.getRow();
      columnIndex = firstCell.getColumn();
      if (this.reversed) {
        this.currentIndex--;
      } else {
        this.currentIndex++;
      }
      return sheet.getRange(rowIndex, columnIndex, 1, this.range.getNumColumns());
    };

    return RangeRowIterator;

  })(RangeAttendantIterator);

  RangeColumnIterator = (function(_super) {
    __extends(RangeColumnIterator, _super);

    function RangeColumnIterator() {
      return RangeColumnIterator.__super__.constructor.apply(this, arguments);
    }

    RangeColumnIterator.prototype.getSize = function() {
      return this.range.getNumColumns();
    };

    RangeColumnIterator.prototype.next = function() {
      var columnIndex, firstCell, rowIndex, sheet;
      sheet = this.range.getSheet();
      firstCell = this.range.getCell(1, this.currentIndex);
      rowIndex = firstCell.getRow();
      columnIndex = firstCell.getColumn();
      if (this.reversed) {
        this.currentIndex--;
      } else {
        this.currentIndex++;
      }
      return sheet.getRange(rowIndex, columnIndex, this.range.getNumRows(), 1);
    };

    return RangeColumnIterator;

  })(RangeAttendantIterator);

  PropertiesAttendant = (function() {
    function PropertiesAttendant() {}

    PropertiesAttendant.prototype.getJSONProperty = function(key) {
      return JSON.parse(PropertiesService.getScriptProperties().getProperty(key));
    };

    PropertiesAttendant.prototype.fetchDeepJSONProperty = function() {
      var fields, key, property;
      key = arguments[0], fields = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      property = this.getJSONProperty(key);
      return AttendantUtilities.fetchDeep.apply(AttendantUtilities, [property].concat(__slice.call(fields)));
    };

    PropertiesAttendant.prototype.setJSONProperty = function(key, value) {
      PropertiesService.getScriptProperties().setProperty(key, JSON.stringify(value));
      return this;
    };

    PropertiesAttendant.prototype.mergePropertyMapping = function(key, map) {
      var mapping;
      mapping = this.getJSONProperty(key);
      if (mapping != null) {
        AttendantUtilities.merge(mapping, map);
        this.setJSONProperty(key, mapping);
      } else {
        this.setJSONProperty(key, map);
      }
      return this;
    };

    return PropertiesAttendant;

  })();

  ScriptPropertiesAttendant = (function(_super) {
    __extends(ScriptPropertiesAttendant, _super);

    function ScriptPropertiesAttendant() {
      return ScriptPropertiesAttendant.__super__.constructor.apply(this, arguments);
    }

    return ScriptPropertiesAttendant;

  })(AttendantUtilities.mixOf(BaseAttendant, PropertiesAttendant));

  UserPropertiesAttendant = (function(_super) {
    __extends(UserPropertiesAttendant, _super);

    function UserPropertiesAttendant() {
      return UserPropertiesAttendant.__super__.constructor.apply(this, arguments);
    }

    return UserPropertiesAttendant;

  })(AttendantUtilities.mixOf(BaseAttendant, PropertiesAttendant));

  DocumentPropertiesAttendant = (function(_super) {
    __extends(DocumentPropertiesAttendant, _super);

    function DocumentPropertiesAttendant() {
      return DocumentPropertiesAttendant.__super__.constructor.apply(this, arguments);
    }

    return DocumentPropertiesAttendant;

  })(AttendantUtilities.mixOf(BaseAttendant, PropertiesAttendant));

  PropertiesServiceAttendant = (function() {
    function PropertiesServiceAttendant() {}

    PropertiesServiceAttendant.__noSuchMethod__ = function(id, args) {
      return AttendantAdapter.proxyMethod(PropertiesService, id, args);
    };

    return PropertiesServiceAttendant;

  })();

  SpreadsheetAppAttendant = (function() {
    function SpreadsheetAppAttendant() {}

    SpreadsheetAppAttendant.DataValidationCriteria = SpreadsheetApp.DataValidationCriteria;

    SpreadsheetAppAttendant.__noSuchMethod__ = function(id, args) {
      return AttendantAdapter.proxyMethod(SpreadsheetApp, id, args);
    };

    return SpreadsheetAppAttendant;

  })();

  Enum = (function() {
    Enum._size = 0;

    Enum._VALUES = {};

    Enum.values = function() {
      var value, values, _i, _len, _ref;
      values = new Array();
      _ref = Object.keys(this._VALUES);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        value = _ref[_i];
        values.push(this._VALUES[value]);
      }
      return values;
    };

    Enum.valueOf = function(name) {
      return this._VALUES[name];
    };

    Enum.prototype._name = void 0;

    Enum.prototype._ordinal = void 0;

    function Enum() {
      var Class;
      Class = this.getSuperclass();
      this._name = Object.keys(Class._VALUES)[Class._size];
      this._ordinal = Class._size;
      Class._size += 1;
      Class._VALUES[this._name] = this;
    }

    Enum.prototype.name = function() {
      return this._name;
    };

    Enum.prototype.ordinal = function() {
      return this._ordinal;
    };

    Enum.prototype.compareTo = function(other) {
      return this._ordinal - other._ordinal;
    };

    Enum.prototype.equals = function(other) {
      return this === other;
    };

    Enum.prototype.toString = function() {
      return this._name;
    };

    Enum.prototype.getClass = function() {
      return this.constructor;
    };

    Enum.prototype.getSuperclass = function() {
      return this.getClass().__super__.constructor;
    };

    return Enum;

  })();

  Severity = (function(_super) {
    __extends(Severity, _super);

    function Severity() {
      return Severity.__super__.constructor.apply(this, arguments);
    }

    Severity._VALUES = {
      DEBUG: Severity.DEBUG,
      INFO: Severity.INFO,
      WARN: Severity.WARN,
      ERROR: Severity.ERROR,
      FATAL: Severity.FATAL
    };

    Severity.DEBUG = new ((function(_super1) {
      __extends(_Class, _super1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      return _Class;

    })(Severity));

    Severity.INFO = new ((function(_super1) {
      __extends(_Class, _super1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      return _Class;

    })(Severity));

    Severity.WARN = new ((function(_super1) {
      __extends(_Class, _super1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      return _Class;

    })(Severity));

    Severity.ERROR = new ((function(_super1) {
      __extends(_Class, _super1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      return _Class;

    })(Severity));

    Severity.FATAL = new ((function(_super1) {
      __extends(_Class, _super1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      return _Class;

    })(Severity));

    return Severity;

  })(Enum);

  LoggerAttendant = (function() {
    var _level;

    function LoggerAttendant() {}

    LoggerAttendant.SEVERITY = Severity;

    _level = LoggerAttendant.SEVERITY.INFO;

    LoggerAttendant.getLevel = function() {
      return _level;
    };

    LoggerAttendant.setLevel = function(value) {
      if (LoggerAttendant.SEVERITY.valueOf(value) != null) {
        _level = value;
      }
      return this;
    };

    LoggerAttendant.isDebug = function() {
      return LoggerAttendant.level.compareTo(LoggerAttendant.SEVERITY.DEBUG) <= 0;
    };

    LoggerAttendant.isInfo = function() {
      return LoggerAttendant.level.compareTo(LoggerAttendant.SEVERITY.INFO) <= 0;
    };

    LoggerAttendant.isWarn = function() {
      return LoggerAttendant.level.compareTo(LoggerAttendant.SEVERITY.WARN) <= 0;
    };

    LoggerAttendant.isError = function() {
      return LoggerAttendant.level.compareTo(LoggerAttendant.SEVERITY.ERROR) <= 0;
    };

    LoggerAttendant.isFatal = function() {
      return LoggerAttendant.level.compareTo(LoggerAttendant.SEVERITY.FATAL) <= 0;
    };

    LoggerAttendant._log = function() {
      var args, formattedMessage, message, severity;
      severity = arguments[0], message = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      if (severity == null) {
        severity = LoggerAttendant.SEVERITY.FATAL;
      }
      if (message == null) {
        message = '';
      }
      if (!(LoggerAttendant.level.compareTo(severity) <= 0)) {
        return this;
      }
      formattedMessage = LoggerAttendant._formatMessage(severity, message);
      Logger.log.apply(Logger, [formattedMessage].concat(__slice.call(args)));
      return this;
    };

    LoggerAttendant._formatMessage = function(severity, message) {
      return "" + (severity.toString()) + ": " + message;
    };

    LoggerAttendant.debug = function() {
      var args, message;
      message = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return LoggerAttendant._log.apply(LoggerAttendant, [LoggerAttendant.SEVERITY.DEBUG, message].concat(__slice.call(args)));
    };

    LoggerAttendant.info = function() {
      var args, message;
      message = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return LoggerAttendant._log.apply(LoggerAttendant, [LoggerAttendant.SEVERITY.INFO, message].concat(__slice.call(args)));
    };

    LoggerAttendant.warn = function() {
      var args, message;
      message = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return LoggerAttendant._log.apply(LoggerAttendant, [LoggerAttendant.SEVERITY.WARN, message].concat(__slice.call(args)));
    };

    LoggerAttendant.error = function() {
      var args, message;
      message = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return LoggerAttendant._log.apply(LoggerAttendant, [LoggerAttendant.SEVERITY.ERROR, message].concat(__slice.call(args)));
    };

    LoggerAttendant.fatal = function() {
      var args, message;
      message = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return LoggerAttendant._log.apply(LoggerAttendant, [LoggerAttendant.SEVERITY.FATAL, message].concat(__slice.call(args)));
    };

    LoggerAttendant.__noSuchMethod__ = function(id, args) {
      return AttendantAdapter.proxyMethod(Logger, id, args);
    };

    return LoggerAttendant;

  })();

  Object.defineProperty(LoggerAttendant, 'level', {
    get: LoggerAttendant.getLevel,
    set: LoggerAttendant.setLevel
  });

  root.SpreadsheetAppAttendant = SpreadsheetAppAttendant;

  root.PropertiesServiceAttendant = PropertiesServiceAttendant;

  root.LoggerAttendant = LoggerAttendant;

}).call(this);
